function createfigure(X1, ymatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data

%  Auto-generated by MATLAB on 08-Feb-2018 09:19:05

% Create figure
figure1 = figure('XVisual',...
    '0x66 (TrueColor, depth 32, RGB mask 0xff0000 0xff00 0x00ff)');

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 1]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1,'Parent',axes1);
set(stairs1(1),'DisplayName','sinusoīda','Color',[0 0 0]);
set(stairs1(2),'MarkerSize',0.5,'Marker','*','LineWidth',4,...
    'Color',[0.854901969432831 0.701960802078247 1],...
    'DisplayName','kosinusoīda');

% Create xlabel
xlabel('t,s');

% Create ylabel
ylabel('U,V');

% Create title
title('Mans pirmais grafiks');

% Create text
text('Parent',axes1,'VerticalAlignment','baseline',...
    'String','textts ko ieliksim ar peles palīdzibu',...
    'Position',[0.0380184331797235 -0.926900584795322 17.3205080756888]);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.549122065260643 0.793163059833599 0.167827298050139 0.0848048327137546]);

